apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.ke.clusterRole.name }}
rules:
  - apiGroups: ["*"]
    resources: ["pods", "nodes", "namespaces", "deployments", "jobs", "cronjobs", "daemonsets", "replicasets", "replicationcontrollers", "statefulsets", "clusterroles", "clusterrolebindings", "componentstatuses", "services", "persistentvolumes", "persistentvolumeclaims", "ingresses", "networkpolicies", "customresourcedefinitions", "globalnetworkpolicies" ]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: [ "serviceaccounts" ]
    verbs: [ "get","list","watch" ]
  - apiGroups: [ "crd.projectcalico.org" ]
    resources: [ "globalnetworkpolicies" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumes", "persistentvolumeclaims" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses", "networkpolicies" ]
    verbs: [ "get", "list", "watch" ]
  {{- if eq .Values.platform "openshift"}}
  - apiGroups: ["operator.openshift.io"]
    resources: ["imagecontentsourcepolicies", "openshiftapiservers", "kubeapiservers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "config.openshift.io" ]
    resources: [ "imagedigestmirrorsets", "imagetagmirrorsets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apps.openshift.io" ]
    resources: [ "deploymentconfigs" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: ["*"]
    resources: ["pods","namespaces"]
    verbs: ["create", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [ "" ]
    resources: [ "endpoints" ]
    verbs: [ "list" ]
  - apiGroups: [ "config.openshift.io" ]
    resources: [ "clusteroperators" ]
    verbs: [ "get", "list" ]
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["get", "list"]
  - apiGroups: ["machineconfiguration.openshift.io"]
    resources: ["machineconfigs", "machineconfigpools"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: [ "pods/log" ]
    verbs: [ "get" ]
  {{- end }}
  - apiGroups: [ "*" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list", "watch", "update", "create", "delete" ]
  - apiGroups: ["aquasecurity.github.io"]
    resources: ["configauditreports", "clusterconfigauditreports"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["*"]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "update", "create"]
  - apiGroups:
      - "*"
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "*"
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
